version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 8080:8080
    volumes:
      - /srv/dev-disk-by-uuid-9c05f480-ef7e-42f7-a650-ce75c2b07cae:/data/KrisBackup
      - /srv/dev-disk-by-uuid-186db084-62ac-4a6f-a9c0-165ed0d40f88:/data/KrisBackupFast
      - ./config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
