---
- name: Deploy and run Docker Compose application
  hosts: raspberrypi
  become: true
  vars:
    app_name: photoview
    compose_project_path: /home/{{ ansible_user }}/{{ app_name }}
    backup_path: /srv/dev-disk-by-uuid-186db084-62ac-4a6f-a9c0-165ed0d40f88/backup-rpi/{{ app_name }}

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker Compose plugin is installed
      apt:
        name: docker-compose-plugin
        state: present

    - name: Create application directory
      file:
        path: "{{ compose_project_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Create backup directory
      file:
        path: "{{ backup_path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy docker-compose.yml to server
      copy:
        src: ./docker-compose.yml
        dest: "{{ compose_project_path }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy .env to server
      copy:
        src: ./.env
        dest: "{{ compose_project_path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Run Docker Compose up
      command: docker compose -f "{{ compose_project_path }}/docker-compose.yml" up -d
      args:
        chdir: "{{ compose_project_path }}"
