---
- name: Install Cockpit and Cockpit PCP on Raspberry Pi
  hosts: raspberrypi
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Cockpit
      apt:
        name: cockpit
        state: present

    - name: Install Cockpit PCP
      apt:
        name: cockpit-pcp
        state: present

    - name: Ensure Cockpit is started and enabled
      systemd:
        name: cockpit
        state: started
        enabled: yes
